version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quality_app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=quality_db
      - DB_USERNAME=quality
      - DB_PASSWORD=E5pum452025*.
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quality-network
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: quality_db
    ports:
      - "3308:3306"  # Cambiado a 3308 para evitar conflicto
    environment:
      - MYSQL_DATABASE=quality_db
      - MYSQL_USER=quality
      - MYSQL_PASSWORD=E5pum452025*.
      - MYSQL_ROOT_PASSWORD=E5pum452025*.
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - quality-network
    restart: unless-stopped

networks:
  quality-network:
    driver: bridge

volumes:
  db-data: