version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_PORT=3307
      - DB_DATABASE=quality_db
      - DB_USERNAME=quality
      - DB_PASSWORD=E5pum452025*.
    depends_on:
      - db
    networks:
      - quality-network
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=quality_db
      - MYSQL_USER=quality
      - MYSQL_PASSWORD=E5pum452025*.
      - MYSQL_ROOT_PASSWORD=E5pum452025*.
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - quality-network
    restart: unless-stopped

networks:
  quality-network:
    driver: bridge

volumes:
  db-data: